# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GlobalInspectionTiles
                                 A QGIS plugin
 This plugin is for classifying samples of pastures areas.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-06-20
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Tharles de Sousa Andrade | LAPIG - UFG
        email                : irtharles@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
from datetime import datetime
from os.path import expanduser, exists

import requests as req
from qgis.core import (
    Qgis,
    QgsFillSymbol,
    QgsProject,
    QgsRasterLayer,
    QgsVectorLayer,
)
from qgis.PyQt.QtCore import QCoreApplication, QSettings, Qt, QTranslator
from qgis.PyQt.QtGui import QIcon, QPixmap
from qgis.PyQt.QtWidgets import (
    QAbstractScrollArea,
    QAction,
    QApplication,
    QFileDialog,
    QMessageBox,
    QScrollArea,
    QVBoxLayout,
)

from .global_inspection_dockwidget import GlobalInspectionTilesDockWidget

# Initialize Qt resources from file resources.py
from .resources import *
from .sources import connections
from .src.inspections import InspectionController
from .src.models.entities import initDb


class GlobalInspectionTiles:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GlobalInspectionTiles_{}.qm'.format(locale),
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr('&Global Inspection Tiles')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar('GlobalInspectionTiles')
        self.toolbar.setObjectName('GlobalInspectionTiles')
        self.pluginSend2Google = None

        # print "** INITIALIZING GlobalInspectionTiles"
        self.pluginIsActive = False
        self.dockwidget = None
        self.scrollarea = None
        self.tilesLayer = None
        self.workDir = None
        self.canvas = None
        self.root = None
        self.group = None
        self.tiles = None
        self.typeInspection = None
        self.currentTileIndex = 0
        self.selectedClassBing = None
        self.selectedClassGoogle = None
        self.currentPixelsLayer = None
        self.inspectionController = None
        self.campaignsConfig = None
        self.layerBing = None
        self.layerGoogle = None
        self.config = initDb()
        self.scroll = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GlobalInspectionTiles', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/global_inspection/icon.png'
        self.add_action(
            icon_path,
            text=self.tr('Inspect Tiles'),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

    # --------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        # print "** CLOSING GlobalInspectionTiles"
        QgsProject.instance().clear()
        self.dockwidget.fieldFileName.setText('')
        self.dockwidget.interpreterName.setText('')
        self.dockwidget.fieldWorkingDirectory.setText('')
        self.dockwidget.imageDate.clear()
        self.iface.actionPan().trigger()

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        self.dockwidget = None

        self.pluginIsActive = False

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        # print "** UNLOAD GlobalInspectionTiles"

        for action in self.actions:
            self.iface.removePluginMenu(self.tr('&Inspection Tiles'), action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    # --------------------------------------------------------------------------
    def open_google_satellite(self):

        url = 'https://mt1.google.com/vt/lyrs=s&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D'
        service_url = url.replace('=', '%3D').replace('&', '%26')
        qgis_tms_uri = 'type=xyz&zmin={0}&zmax={1}&url={2}'.format(
            0, 19, service_url
        )

        layer = QgsRasterLayer(qgis_tms_uri, 'Google', 'wms')
        self.layerGoogle = layer
        if layer.isValid():
            QgsProject.instance().addMapLayer(layer)
            QgsProject.instance().layerTreeRoot().findLayer(
                layer.id()
            ).setItemVisibilityChecked(False)
        else:
            print('Layer failed to load!')

    def open_bing_satellite(self):

        url = 'http://ecn.t3.tiles.virtualearth.net/tiles/a{q}.jpeg?g=1'

        qgis_tms_uri = 'type=xyz&zmin={0}&zmax={1}&url={2}'.format(0, 19, url)

        layer = QgsRasterLayer(qgis_tms_uri, 'Bing', 'wms')
        self.layerBing = layer

        if layer.isValid():
            QgsProject.instance().addMapLayer(layer)
            QgsProject.instance().layerTreeRoot().findLayer(
                layer.id()
            ).setItemVisibilityChecked(False)
        else:
            print('Layer failed to load!')

    def get_config(self, key):
        """Load config file and get value of key"""
        return getattr(self.config, key)

    def set_config(self, key, value):
        """Write config in config file"""
        setattr(self.config, key, value)
        self.config.save()

    def load_type_inspections(self):
        """Load campaigns from service: https://ows.lapig.iesa.ufg.br/api/global-pasture/campaigns"""
        resp = req.get(
            'https://ows.lapig.iesa.ufg.br/api/global-pasture/campaigns'
        )
        self.campaignsConfig = resp.json()[0]

    def config_tiles(self):
        tile = self.tiles[self.currentTileIndex]
        self.dockwidget.tileInfoBing.setText(
            f'Tile {self.currentTileIndex + 1} of {len(self.tiles)}'
        )
        self.dockwidget.tileInfoGoogle.setText(
            f'Tile {self.currentTileIndex + 1} of {len(self.tiles)}'
        )

        self.inspectionController.create_grid_pixels(tile)

    def load_tiles(self):
        QApplication.instance().setOverrideCursor(Qt.BusyCursor)
        """Load tiles from layer"""
        instance = QgsProject.instance()
        openLayers = [layer for layer in instance.mapLayers().values()]
        for layer in openLayers:
            if layer.name() == 'tiles':
                self.tiles = [f.attributes() for f in layer.getFeatures()]
        QApplication.instance().setOverrideCursor(Qt.ArrowCursor)

    def open_tiles_file(self, fromConfig=False):
        QApplication.instance().setOverrideCursor(Qt.BusyCursor)

        """Open Tiles file Dialog"""

        if fromConfig:
            layerPath = self.get_config('filePath')
            self.dockwidget.tabWidget.setCurrentIndex(1)
            self.currentTileIndex = self.get_config('currentTileIndex')
        else:
            layerPath = str(
                QFileDialog.getOpenFileName(
                    caption='Escolha o arquivo com os tiles',
                    filter='Geopackage (*gpkg)',
                )[0]
            )
        if layerPath != '' and exists(layerPath):
            self.tilesLayer = QgsVectorLayer(layerPath, 'tiles', 'ogr')
            symbol = QgsFillSymbol.createSimple(
                {
                    'color': '0,0,0,0',
                    'color_border': 'red',
                    'width_border': '0.5',
                    'style': 'dashed_line',
                }
            )
            self.tilesLayer.renderer().setSymbol(symbol)
            self.dockwidget.fieldFileName.setText(layerPath)
            QgsProject.instance().addMapLayer(self.tilesLayer)
            self.iface.setActiveLayer(self.tilesLayer)
            self.iface.zoomToActiveLayer()
            self.load_tiles()
            self.set_config(key='filePath', value=layerPath)

            if fromConfig:
                self.config_tiles()

            return True

        else:
            self.iface.messageBar().pushMessage(
                'ERROR READ FILE',
                'Tiles GPKG not found',
                level=Qgis.Critical,
                duration=5,
            )
            QApplication.instance().setOverrideCursor(Qt.ArrowCursor)
            return False

        QApplication.instance().setOverrideCursor(Qt.ArrowCursor)

    def get_dir_path(self, fromConfig=False):
        if fromConfig:
            dir = self.get_config('workingDirectory')
        else:
            dir = QFileDialog.getExistingDirectory(
                self.dockwidget,
                'Select Directory',
                expanduser('~'),
                QFileDialog.ShowDirsOnly,
            )
            self.dockwidget.btnInitInspections.setVisible(True)
        self.dockwidget.fieldWorkingDirectory.setText(dir)
        self.set_config(key='workingDirectory', value=dir)

    def load_classes(self):
        imageDate = self.dockwidget.imageDate.date()

        # possibleWrongDate = datetime(2000, 1, 1)

        # if imageDate == possibleWrongDate:
        #     msg = QMessageBox()
        #     msg.setIcon(QMessageBox.Question)
        #     msg.setText("Is the date entered correct?")
        #     msg.setWindowTitle("DATE VALIDATION")
        #     msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        #     retval = msg.exec_()
        #     if retval != 16384:
        #         return

        if not self.inspectionController.date_is_valid(
            imageDate.toString('yyyy-MM-dd')
        ):
            imageDate = None

        if not imageDate:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Question)
            msg.setText('The image date is required to classify this tile!')
            msg.setInformativeText(
                'If the image date was not found, the tile would be ignored. Do you confirm the missing date of the image?'
            )
            msg.setWindowTitle('INSPECTION TILES')
            msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
            retval = msg.exec_()
            if retval == 16384:
                self.inspectionController.init_inspection_tile(
                    no_image_date=True
                )
        else:
            if self.get_config('imageSource') == 'BING':
                self.dockwidget.labelClassBing.setVisible(True)
                self.dockwidget.selectedClassBing.setVisible(True)
            else:
                self.dockwidget.btnNext.setVisible(True)
                self.dockwidget.importBingClassification.setVisible(True)
                self.dockwidget.labelClassGoogle.setVisible(True)
                self.dockwidget.selectedClassGoogle.setVisible(True)

            self.inspectionController.init_inspection_tile()

    def init_inspections(self):
        interpreterName = self.dockwidget.interpreterName.text()

        if interpreterName != '':
            QApplication.instance().setOverrideCursor(Qt.BusyCursor)

            self.config_tiles()
            self.set_config(
                key='interpreterName', value=interpreterName.upper()
            )
            self.dockwidget.btnInitInspections.setVisible(False)

            if self.get_config('imageSource') == 'BING':
                self.dockwidget.tabWidget.setTabEnabled(1, True)
                self.dockwidget.tabWidget.setCurrentIndex(1)

            else:
                self.dockwidget.tabWidget.setTabEnabled(2, True)
                self.dockwidget.tabWidget.setCurrentIndex(2)

        else:
            self.iface.messageBar().pushMessage(
                '',
                f'The name of interpreter is required!',
                level=Qgis.Critical,
                duration=5,
            )

    def run(self):
        """Run method that loads and starts the plugin"""
        if not self.pluginIsActive:
            # print "** STARTING GlobalInspectionTiles"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = GlobalInspectionTilesDockWidget()

            self.dockwidget.btnPointDate.setIcon(
                QIcon(os.path.dirname(__file__) + '/img/copy-point.png')
            )
            self.dockwidget.btnClearSelectionBing.setIcon(
                QIcon(os.path.dirname(__file__) + '/img/delete.png')
            )
            self.dockwidget.btnClearSelectionGoogle.setIcon(
                QIcon(os.path.dirname(__file__) + '/img/delete.png')
            )
            self.dockwidget.logo.setPixmap(
                QPixmap(os.path.dirname(__file__) + '/img/logo-plugin.png')
            )
            self.dockwidget.btnNext.setIcon(
                QIcon(os.path.dirname(__file__) + '/img/save.png')
            )
            self.iface.actionPan().trigger()

            connections.xyz(self)
            self.inspectionController = InspectionController(self)

            self.workDir = (
                str.split(__file__, 'global_inspection.py')[0] + 'datasource'
            )
            self.pluginIsActive = True
            self.canvas = self.iface.mapCanvas()

            QgsProject.instance().clear()

            self.dockwidget.btnInitInspections.setVisible(False)
            self.dockwidget.btnClearSelectionBing.setVisible(False)
            self.dockwidget.btnClearSelectionGoogle.setVisible(False)
            self.dockwidget.btnLoadClasses.setVisible(False)
            self.dockwidget.tabWidget.setTabEnabled(1, False)
            self.dockwidget.tabWidget.setTabEnabled(2, False)
            self.dockwidget.tabWidget.setTabEnabled(3, False)
            self.dockwidget.labelClassBing.setVisible(False)
            self.dockwidget.labelClassGoogle.setVisible(False)
            self.dockwidget.selectedClassBing.setVisible(False)
            self.dockwidget.selectedClassGoogle.setVisible(False)
            self.dockwidget.classesBing.setVisible(False)
            self.dockwidget.classesGoogle.setVisible(False)
            self.dockwidget.importBingClassification.setVisible(False)
            self.dockwidget.btnFinishBing.setVisible(False)
            self.dockwidget.bingStartDate.setEnabled(False)
            self.dockwidget.btnNext.setVisible(False)
            self.dockwidget.btnNext.setEnabled(False)
            self.dockwidget.bingEndDate.setEnabled(False)
            self.dockwidget.imageDate.setMaximumDateTime(datetime.now())

            self.load_type_inspections()
            self.open_google_satellite()
            self.open_bing_satellite()

            file = self.get_config('filePath')

            if file != '':
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Question)
                msg.setText('Do you want to start a new inspection?')
                msg.setWindowTitle('INSPECTION TILES')
                msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
                QApplication.instance().setOverrideCursor(Qt.ArrowCursor)
                retval = msg.exec_()
                # 65536 -> No | 16384 -> Yes
                if retval == 16384:
                    self.dockwidget.btnFile.setEnabled(True)
                    self.dockwidget.btnWorkingDirectory.setEnabled(True)
                    self.dockwidget.interpreterName.setEnabled(True)
                    self.dockwidget.tabWidget.setCurrentIndex(0)
                    self.set_config(key='currentTileIndex', value=0)
                    self.set_config(key='filePath', value='')
                    self.set_config(key='workingDirectory', value='')
                    self.set_config(key='interpreterName', value='')
                    self.set_config(key='imageSource', value='BING')
                else:
                    self.get_dir_path(fromConfig=True)
                    if not self.open_tiles_file(fromConfig=True):
                        return
                    self.dockwidget.interpreterName.setText(
                        self.get_config('interpreterName').upper()
                    )
                    self.dockwidget.tabWidget.setTabEnabled(1, True)
                    self.dockwidget.tabWidget.setTabEnabled(2, True)

                    self.set_config(key='imageSource', value='BING')
                    self.inspectionController.on_change_tab(1)

                    self.dockwidget.interpreterName.setEnabled(False)
                    self.dockwidget.btnFile.setEnabled(False)
                    self.dockwidget.btnWorkingDirectory.setEnabled(False)
                    self.dockwidget.btnInitInspections.setVisible(False)

            self.dockwidget.btnFile.clicked.connect(self.open_tiles_file)
            self.dockwidget.btnWorkingDirectory.clicked.connect(
                self.get_dir_path
            )
            self.dockwidget.btnClearSelectionBing.clicked.connect(
                self.inspectionController.remove_selection
            )
            self.dockwidget.btnClearSelectionGoogle.clicked.connect(
                self.inspectionController.remove_selection
            )
            self.dockwidget.btnInitInspections.clicked.connect(
                self.init_inspections
            )
            self.dockwidget.btnLoadClasses.clicked.connect(self.load_classes)
            self.dockwidget.btnFinishBing.clicked.connect(
                self.inspectionController.start_inspection_google
            )
            self.dockwidget.tabWidget.currentChanged.connect(
                self.inspectionController.on_change_tab
            )
            self.dockwidget.sameImage.toggled.connect(
                self.inspectionController.set_same_image
            )
            self.dockwidget.importBingClassification.clicked.connect(
                self.inspectionController.import_classes_bing
            )

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # add scroll

            scroll_tab = QScrollArea()
            scroll_tab.setSizeAdjustPolicy(
                QAbstractScrollArea.AdjustToContents
            )
            self.dockwidget.tabWidget.setMinimumHeight(750)
            scroll_tab.setWidget(self.dockwidget.tabWidget)

            self.dockwidget.gridMain.addWidget(scroll_tab)

            # show the dockwidget
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
