# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GlobalInspectionTiles
                                 A QGIS plugin
 This plugin is for classifying samples of pastures areas.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-06-20
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Tharles de Sousa Andrade | LAPIG - UFG
        email                : irtharles@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox
from qgis.core import Qgis, QgsProject, QgsRasterLayer, QgsVectorLayer, QgsFillSymbol, QgsField
from qgis.utils import plugins
# Initialize Qt resources from file resources.py
from .resources import *
from .sources import connections
from .src.inspections import InspectionController

# Import the code for the DockWidget
from .global_inspection_dockwidget import GlobalInspectionTilesDockWidget
from os import path
from os.path import expanduser
import json
import os
import requests as req


class GlobalInspectionTiles:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GlobalInspectionTiles_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Global Inspection Tiles')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'GlobalInspectionTiles')
        self.toolbar.setObjectName(u'GlobalInspectionTiles')
        self.pluginSend2Google = None

        if 'send2google_earth' in plugins:
            self.pluginSend2Google = plugins['send2google_earth']

        # print "** INITIALIZING GlobalInspectionTiles"
        self.pluginIsActive = False
        self.dockwidget = None
        self.tilesLayer = None
        self.workDir = None
        self.canvas = None
        self.root = None
        self.group = None
        self.tiles = None
        self.typeInspection = None
        self.currentTileIndex = 0
        self.selectedClass = None
        self.currentPixelsLayer = None
        self.inspectionController = None
        self.geometryType = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GlobalInspectionTiles', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/global_inspection/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Inspect Tiles'),
            callback=self.run,
            parent=self.iface.mainWindow())

    # --------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        # print "** CLOSING GlobalInspectionTiles"
        QgsProject.instance().clear()
        self.dockwidget.fieldFileName.setText("")
        self.dockwidget.interpreterName.setText("")
        self.dockwidget.fieldWorkingDirectory.setText("")
        self.dockwidget.imageDate.setText("")
        self.iface.actionPan().trigger() 

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        self.dockwidget = None

        self.pluginIsActive = False

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        # print "** UNLOAD GlobalInspectionTiles"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Inspection Tiles'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    # --------------------------------------------------------------------------
    def openGoogleSatellite(self):

        url = 'https://mt1.google.com/vt/lyrs=s&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D'
        service_url = url.replace("=", "%3D").replace("&", "%26")
        qgis_tms_uri = 'type=xyz&zmin={0}&zmax={1}&url={2}'.format(0, 19, service_url)

        layer = QgsRasterLayer(qgis_tms_uri, "Google Satellite", 'wms')

        if layer.isValid():
            QgsProject.instance().addMapLayer(layer)
        else:
            print("Layer failed to load!")

    def getConfig(self, key):
        """Load config file and get value of key"""
        data = None
        with open(self.workDir + 'config.json') as json_file:
            ob = json.load(json_file)
            data = ob[key]
            json_file.close()
        return data

    def setConfig(self, key, value):
        """Write config in config file"""
        ob = None
        with open(self.workDir + 'config.json', 'r') as json_file:
            ob = json.load(json_file)
            json_file.close()

        with open(self.workDir + 'config.json', 'w') as outfile:
            ob[key] = value
            json.dump(ob, outfile)
            outfile.close()

    def loadTypeInspections(self):
        """Load campaigns from service: https://ows.lapig.iesa.ufg.br/api/global-pasture/campaigns"""
        self.dockwidget.cbTypeInspection.clear()
        resp = req.get('https://ows.lapig.iesa.ufg.br/api/global-pasture/campaigns')
        campaigns = resp.json()
        for campaign in campaigns:
            self.dockwidget.cbTypeInspection.addItem(campaign['title'], campaign)

    def configTiles(self):
        tile = self.tiles[self.currentTileIndex]
        self.dockwidget.tileInfo.setText(f"Tile {tile[0]} of {len(self.tiles)}")        
        filename = path.normpath(f"{self.dockwidget.fieldWorkingDirectory.text()}/{tile[0]}_{self.typeInspection['_id']}.gpkg") 
       
        if path.exists(filename):
            self.inspectionController.loadTileFromFile(tile)
        else:
            if (self.typeInspection['classes'][0]['type'] == 'polygon'):
                self.inspectionController.createGridPixels(tile)
            else:
                self.inspectionController.createPointsLayer(tile)

    def loadTiles(self):
        """Load tiles from layer"""
        instance = QgsProject.instance()
        openLayers = [layer for layer in instance.mapLayers().values()]
        for layer in openLayers:
            if (layer.name() == 'tiles'):
                self.tiles = [f.attributes() for f in layer.getFeatures()]

    def openTilesFile(self, fromConfig=False):
        """Open Tiles file Dialog"""
       
        if (fromConfig):
            layerPath = self.getConfig('filePath')
            self.dockwidget.tabWidget.setCurrentIndex(1)
            self.currentTileIndex = self.getConfig('currentTileIndex')
            # self.inspectionController.initInspectionTile()
        else:
            layerPath = str(
                QFileDialog.getOpenFileName(
                    caption='Escolha o arquivo com os tiles',
                    filter='Geopackage (*gpkg)'
                )[0]
            )
        if (layerPath != ""):
            self.tilesLayer = QgsVectorLayer(layerPath, 'tiles', 'ogr')
            symbol = QgsFillSymbol.createSimple(
                {'color': '0,0,0,0', 'color_border': 'red', 'width_border': '0.5', 'style': 'dashed_line'})
            self.tilesLayer.renderer().setSymbol(symbol)
            self.dockwidget.fieldFileName.setText(layerPath)
            QgsProject.instance().addMapLayer(self.tilesLayer)
            self.iface.setActiveLayer(self.tilesLayer);
            self.iface.zoomToActiveLayer();
            self.loadTiles()
            self.setConfig(key='filePath', value=layerPath)
            
            if(fromConfig):
                 self.configTiles()


    def getDirPath(self, fromConfig=False):
        if (fromConfig):
            dir = self.getConfig('workingDirectory')
        else:
            dir = QFileDialog.getExistingDirectory(
                self.dockwidget,
                "Select Directory",
                expanduser("~"),
                QFileDialog.ShowDirsOnly
            )
            self.dockwidget.btnInitInspections.setVisible(True)
        self.dockwidget.fieldWorkingDirectory.setText(dir)
        self.setConfig(key='workingDirectory', value=dir)

    def onChangeBTypeInspection(self, index):
        if (index >= 0):
            self.typeInspection = self.dockwidget.cbTypeInspection.itemData(index)
            self.setConfig(key='currentInspectionType', value=index)
            self.geometryType = self.typeInspection['classes'][0]['type'];
            self.inspectionController.clearContainerClasses()

    def loadClasses(self):
        imageDate = self.dockwidget.imageDate.text()
        if not self.inspectionController.dateIsValid(imageDate):
            imageDate = None

        if not imageDate:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("The image date is required to classify this tile!")
            msg.setInformativeText("If the image date was not found, the tile would be ignored. Do you confirm the missing date of the image?")
            msg.setWindowTitle("INSPECTION TILES")
            msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
            retval = msg.exec_()
            if (retval == 16384):
                self.inspectionController.initInspectionTile(noImageDate=True)
        else:
            self.dockwidget.labelClass.setVisible(True)
            self.dockwidget.selectedClass.setVisible(True)
            self.inspectionController.initInspectionTile()

    def initInspections(self):
        interpreterName =  self.dockwidget.interpreterName.text()
        if(interpreterName != ""): 
            self.configTiles()
            self.dockwidget.tabWidget.setTabEnabled(1, True)
            self.dockwidget.tabWidget.setCurrentIndex(1)
            self.dockwidget.btnInitInspections.setVisible(False)
            self.setTileInfoVisible(visible=True)
            self.setConfig(key='interpreterName', value=interpreterName.upper())
        else: 
            self.iface.messageBar().pushMessage("", f"The name of interpreter is required!", level=Qgis.Critical, duration=5)    


    def setTileInfoVisible(self, visible):
        # self.dockwidget.btnBack.setVisible(visible)
        self.dockwidget.tileInfo.setVisible(visible)
        self.dockwidget.btnNext.setVisible(visible)

    def run(self):
        """Run method that loads and starts the plugin"""
        if not self.pluginIsActive:
            # print "** STARTING GlobalInspectionTiles"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = GlobalInspectionTilesDockWidget()
            
            self.dockwidget.btnPointDate.setIcon(QIcon(os.path.dirname(__file__) + "/img/copy-point.png"))
            self.dockwidget.btnClearSelection.setIcon(QIcon(os.path.dirname(__file__) + "/img/delete.png"))
            # self.dockwidget.btnBack.setIcon(QIcon(os.path.dirname(__file__) + "/img/back.png"))
            self.dockwidget.btnNext.setIcon(QIcon(os.path.dirname(__file__) + "/img/save.png"))
            self.dockwidget.btnBack.setEnabled(False)
            self.dockwidget.btnNext.setEnabled(False)
            self.iface.actionPan().trigger() 

            connections.xyz(self)
            self.inspectionController = InspectionController(self)
           
            self.workDir = str.split(__file__, "global_inspection.py")[0]
            self.pluginIsActive = True
            self.canvas = self.iface.mapCanvas()
            QgsProject.instance().clear()

            # QgsProject.instance().clear()
            # Check if config file exists, if not create
            if not os.path.exists(self.workDir + 'config.json'):
                with open(self.workDir + 'config.json', 'w') as file:
                    config = {"currentInspectionType": 0, "currentTileIndex": 0, "interpreterName": "", "filePath": "", "workingDirectory": ""}
                    json.dump(config, file, sort_keys=True)
                    file.close()

            self.setTileInfoVisible(visible=False)
            self.dockwidget.btnInitInspections.setVisible(False)
            self.dockwidget.btnClearSelection.setVisible(False)
            self.dockwidget.btnLoadClasses.setVisible(False)
            self.dockwidget.tabWidget.setTabEnabled(1, False)
            self.dockwidget.labelClass.setVisible(False)
            self.dockwidget.selectedClass.setVisible(False)
            self.loadTypeInspections()

            self.openGoogleSatellite()

            currentInspectionType = self.getConfig('currentInspectionType')
            self.typeInspection = self.dockwidget.cbTypeInspection.itemData(currentInspectionType)
            self.dockwidget.cbTypeInspection.setCurrentIndex(currentInspectionType)

            file = self.getConfig('filePath')

            if (file != ""):
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Warning)
                msg.setText("Do you want to start a new inspection?")
                msg.setWindowTitle("INSPECTION TILES")
                msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
                retval = msg.exec_()
                # 65536 -> No | 16384 -> Yes
                if (retval == 16384):
                    self.dockwidget.cbTypeInspection.setEnabled(True)
                    self.dockwidget.btnFile.setEnabled(True)
                    self.dockwidget.btnWorkingDirectory.setEnabled(True)
                    self.dockwidget.interpreterName.setEnabled(True)
                    self.dockwidget.tabWidget.setCurrentIndex(0)
                    self.setConfig(key='currentInspectionType', value=0)
                    self.setConfig(key='currentTileIndex', value=0)
                    self.setConfig(key='filePath', value="")
                    self.setConfig(key='workingDirectory', value="")
                    self.setConfig(key='interpreterName', value="")
                    
                else:
                    self.getDirPath(fromConfig=True)
                    self.openTilesFile(fromConfig=True)
                    self.dockwidget.interpreterName.setText(self.getConfig('interpreterName').upper())
                    self.dockwidget.tabWidget.setTabEnabled(1, True)
                    self.dockwidget.interpreterName.setEnabled(False)
                    self.dockwidget.cbTypeInspection.setEnabled(False)
                    self.dockwidget.btnFile.setEnabled(False)
                    self.dockwidget.btnWorkingDirectory.setEnabled(False)
                    self.dockwidget.btnInitInspections.setVisible(False)
                    self.setTileInfoVisible(visible=True)

            self.dockwidget.btnFile.clicked.connect(self.openTilesFile)
            self.dockwidget.btnWorkingDirectory.clicked.connect(self.getDirPath)
            self.dockwidget.cbTypeInspection.currentIndexChanged.connect(self.onChangeBTypeInspection)
            self.dockwidget.btnClearSelection.clicked.connect(self.inspectionController.removeSelection)
            self.dockwidget.btnInitInspections.clicked.connect(self.initInspections)
            self.dockwidget.btnLoadClasses.clicked.connect(self.loadClasses)

            self.geometryType = self.typeInspection['classes'][0]['type'];
            
            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
